# coding=utf-8

from service.web.web_welcome import web_welcomeImpl
from service.web.web_look import web_lookImpl
from service.web.web_student_info import web_student_infoImpl
from service.web.web_change_password import web_change_passwordImpl
from service.web.web_student_register import web_student_registerImpl
from service.web.web_register_con import web_register_conImpl
from service.web.web_admin_info import web_admin_infoImpl
from service.web.web_student_management import web_student_managementImpl
from service.web.web_major_management import web_major_managementImpl
from service.web.web_register_check import web_register_checkImpl
from service.web.web_company_management import web_company_managementImpl


from service.api.api_getAllAccountInfo import api_getAllAccountInfoImpl
from service.api.api_login import api_loginImpl
from service.api.api_change_password import api_change_passwordImpl
from service.api.api_register import api_registerImpl
from service.api.api_student_management import api_student_managementImpl
from service.api.api_major_management import api_major_managementImpl
from service.api.api_register_check import api_register_checkImpl
from service.api.api_company_management import api_company_managementImpl
from service.api.api_delete_register import api_delete_registerImpl